import { config } from './config.js';
import { CopyTrader } from './copyTrader.js';
import { createServer, startServer } from './server.js';
import { Storage } from './storage.js';
import { initWalletManager } from './walletManager.js';
import { startMonitoringServices } from './startup.js';
import { initDatabase } from './database.js';
import { DiscoveryManager } from './discovery/discoveryManager.js';
import { clearDiscoveryRuntimeHeartbeat } from './discovery/discoveryRuntimeState.js';
import { getRuntimeServicesForMode, resolveRuntimeMode } from './runtimeMode.js';
import type { Server } from 'node:http';
import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';
import { createComponentLogger } from './logger.js';

const log = createComponentLogger('Index');

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get project root - works whether running from src/ or dist/
const PROJECT_ROOT = process.cwd();

/**
 * Interactive setup - asks for configuration one step at a time
 */
async function runInteractiveSetup(): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false  // Disable special character handling for better paste support
  });

  const question = (prompt: string): Promise<string> => {
    return new Promise((resolve) => {
      process.stdout.write(prompt);
      rl.once('line', (answer) => {
        resolve(answer);
      });
    });
  };

  log.info('\n');
  log.info('═'.repeat(60));
  log.info('   🚀 POLYMARKET COPYTRADE BOT - FIRST TIME SETUP');
  log.info('═'.repeat(60));
  log.info('\nLet\'s get your bot configured! I\'ll ask for each value one at a time.\n');

  try {
    // Step 1: Private Key
    log.info('─'.repeat(60));
    log.info('STEP 1 of 4: Your Wallet Private Key');
    log.info('─'.repeat(60));
    log.info('\nThis is the private key from your crypto wallet.');
    log.info('It should start with "0x" and be 66 characters long.');
    log.info('\n⚠️  IMPORTANT: Never share this with anyone!\n');

    const privateKey = await question('Enter your private key: ');

    if (!privateKey || !privateKey.trim()) {
      log.info('\n❌ Private key is required. Setup cancelled.\n');
      rl.close();
      return false;
    }

    const trimmedKey = privateKey.trim();

    // Basic validation
    if (!trimmedKey.startsWith('0x')) {
      log.info('\n⚠️  Warning: Private key usually starts with "0x"');
    }
    if (trimmedKey.length !== 66) {
      log.info(`⚠️  Warning: Private key length is ${trimmedKey.length}, expected 66`);
    }

    // Step 2: Builder API Key
    log.info('\n');
    log.info('─'.repeat(60));
    log.info('STEP 2 of 4: Polymarket Builder API Key');
    log.info('─'.repeat(60));
    log.info('\nGo to: https://polymarket.com/settings?tab=builder');
    log.info('Click "Create API Key" and copy the API Key here.\n');
    log.info('(This is REQUIRED for trading to work)\n');

    const builderApiKey = await question('Enter your Builder API Key: ');

    if (!builderApiKey || !builderApiKey.trim()) {
      log.info('\n⚠️  Warning: Without Builder API credentials, trading will fail!');
    }

    // Step 3: Builder Secret
    log.info('\n');
    log.info('─'.repeat(60));
    log.info('STEP 3 of 4: Polymarket Builder API Secret');
    log.info('─'.repeat(60));
    log.info('\nThis is shown once when you create the API key.');
    log.info('If you didn\'t save it, you may need to create a new key.\n');

    const builderSecret = await question('Enter your Builder API Secret: ');

    // Step 4: Builder Passphrase
    log.info('\n');
    log.info('─'.repeat(60));
    log.info('STEP 4 of 4: Polymarket Builder API Passphrase');
    log.info('─'.repeat(60));
    log.info('\nThis is the passphrase you created with your API key.\n');

    const builderPassphrase = await question('Enter your Builder API Passphrase: ');

    rl.close();

    // Create the .env file
    const apiSecret = [...Array(32)].map(() => Math.random().toString(36)[2]).join('');
    const envContent = `# Polymarket Copytrade Bot Configuration
# Generated by setup wizard

# API Authentication — protects your dashboard and API endpoints
# Anyone accessing the dashboard will be prompted for this secret.
API_SECRET=${apiSecret}

# Your wallet private key (NEVER commit this to git!)
PRIVATE_KEY=${trimmedKey}

# Polymarket Builder API credentials (REQUIRED for trading!)
# Get these from: https://polymarket.com/settings?tab=builder
POLYMARKET_BUILDER_API_KEY=${builderApiKey?.trim() || ''}
POLYMARKET_BUILDER_SECRET=${builderSecret?.trim() || ''}
POLYMARKET_BUILDER_PASSPHRASE=${builderPassphrase?.trim() || ''}

# Polymarket API endpoints (use defaults)
POLYMARKET_CLOB_API_URL=https://clob.polymarket.com
POLYMARKET_DATA_API_URL=https://data-api.polymarket.com
POLYMARKET_GAMMA_API_URL=https://gamma-api.polymarket.com

# Polygon RPC endpoint
POLYGON_RPC_URL=https://polygon-rpc.com

# Signature type (0 = EOA wallet, 1 = Proxy wallet, 2 = Gnosis Safe)
# If you connected MetaMask directly, use 0
# If you signed up via email, use 1
POLYMARKET_SIGNATURE_TYPE=0

# Server configuration
PORT=3001

# Monitoring interval (5 seconds for fast copy trading)
MONITORING_INTERVAL_MS=5000

# Data directory
DATA_DIR=./data
`;

    // Write to .env file in project root
    const envPath = join(PROJECT_ROOT, '.env');

    log.info(`\n[DEBUG] Writing .env to: ${envPath}`);

    writeFileSync(envPath, envContent, 'utf-8');

    log.info('\n');
    log.info('═'.repeat(60));
    log.info('   ✅ SETUP COMPLETE!');
    log.info('═'.repeat(60));
    log.info(`\nYour configuration has been saved to: ${envPath}`);
    log.info('\nRestarting bot with your new configuration...\n');

    return true;

  } catch (error: any) {
    log.error({ detail: error.message }, '\n❌ Setup failed')
    rl.close();
    return false;
  }
}

/**
 * Check if configuration exists and is valid
 */
function isConfigured(): boolean {
  const envPath = join(PROJECT_ROOT, '.env');

  log.info(`[DEBUG] Checking for .env at: ${envPath}`);

  // Check if .env file exists
  if (!existsSync(envPath)) {
    log.info(`[DEBUG] .env file does not exist`);
    return false;
  }

  // Check if PRIVATE_KEY is set (not just placeholder)
  try {
    const envContent = readFileSync(envPath, 'utf-8');
    // Just check that PRIVATE_KEY has some value (not empty or placeholder)
    const hasPrivateKey = envContent.includes('PRIVATE_KEY=') &&
      !envContent.includes('PRIVATE_KEY=your_private_key_here') &&
      !envContent.includes('PRIVATE_KEY=\n') &&
      !envContent.includes('PRIVATE_KEY=$');
    log.info(`[DEBUG] .env exists, hasPrivateKey: ${hasPrivateKey}`);
    return hasPrivateKey;
  } catch (err) {
    log.info(`[DEBUG] Error reading .env: ${err}`);
    return false;
  }
}

/**
 * Reload config after setup
 */
function reloadConfig(): void {
  // Re-read .env file
  const envPath = join(PROJECT_ROOT, '.env');

  if (existsSync(envPath)) {
    const envContent = readFileSync(envPath, 'utf-8');
    const lines = envContent.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...valueParts] = trimmed.split('=');
        const value = valueParts.join('='); // Handle values with = in them
        if (key && value !== undefined) {
          process.env[key] = value;
        }
      }
    }
  }

  // Update config object
  config.privateKey = process.env.PRIVATE_KEY || '';
  config.polymarketBuilderApiKey = process.env.POLYMARKET_BUILDER_API_KEY || '';
  config.polymarketBuilderSecret = process.env.POLYMARKET_BUILDER_SECRET || '';
  config.polymarketBuilderPassphrase = process.env.POLYMARKET_BUILDER_PASSPHRASE || '';
}

const registerAppShutdown = (copyTrader: CopyTrader | null, server: Server | null): void => {
  const handleShutdown = async () => {
    console.log('\n🛑 Shutting down...');
    try {
      if (copyTrader) {
        copyTrader.stop();
      }
      if (server) {
        await new Promise<void>((resolve, reject) => {
          const timeout = setTimeout(() => reject(new Error('Timed out waiting for HTTP server to close')), 5000);
          server.close((error) => {
            clearTimeout(timeout);
            if (error) {
              reject(error);
              return;
            }
            resolve();
          });
        });
      }
    } catch (error: any) {
      log.error({ detail: error?.message }, 'Shutdown encountered an error');
    } finally {
      process.exit(0);
    }
  };

  process.on('SIGINT', handleShutdown);
  process.on('SIGTERM', handleShutdown);
};

const registerDiscoveryShutdown = (discoveryManager: DiscoveryManager): void => {
  const handleShutdown = async () => {
    console.log('\n🛑 Shutting down discovery worker...');
    try {
      await discoveryManager.stop();
    } finally {
      process.exit(0);
    }
  };

  process.on('SIGINT', handleShutdown);
  process.on('SIGTERM', handleShutdown);
};

async function startAppRuntime() {
  let copyTrader: CopyTrader | null = null;
  let server: Server | null = null;

  try {
    // Ensure data directory exists (always do this, even if config fails)
    await Storage.ensureDataDir();

    // Check if configuration exists
    if (!isConfigured()) {
      log.info('\n🔧 No configuration found. Starting setup wizard...');

      const setupSuccess = await runInteractiveSetup();

      if (!setupSuccess) {
        log.info('\n❌ Setup was not completed. Please run "npm run dev" again to try setup.\n');
        process.exit(1);
      }

      // Reload configuration after setup
      reloadConfig();
    }

    // Initialize wallet manager early (so trading wallets are available to API routes)
    log.info('🔑 Loading trading wallets...');
    await initWalletManager();

    // Create and start web server first (so it's accessible even if bot init fails)
    log.info('🌐 Starting web server...');
    copyTrader = new CopyTrader();
    const app = await createServer(copyTrader);
    server = await startServer(app);

    // Validate configuration
    log.info('🔧 Validating configuration...');
    try {
      config.validate();
    } catch (error: any) {
      log.error({ detail: error.message }, '⚠️  Configuration validation failed')
      log.error('⚠️  Bot will not start, but web server is running.');
      log.error('⚠️  Please fix your configuration and restart.');
      // Don't exit - let the server keep running so user can see the error
      return;
    }

    // Initialize copy trader
    log.info('🚀 Initializing copy trader...');
    try {
      await copyTrader.initialize();

      // Check if there are any tracked wallets
      const trackedWallets = await Storage.getActiveWallets();
      const activeWallets = trackedWallets.filter((w: { active: boolean }) => w.active);

      log.info(`\n${'='.repeat(60)}`);
      log.info(`📊 BOT STATUS`);
      log.info(`${'='.repeat(60)}`);

      if (trackedWallets.length === 0) {
        log.info('\n⚠️  WARNING: No wallets are being tracked!');
        log.info('   To start copy trading:');
        log.info('   1. Open the web dashboard at http://localhost:' + config.port);
        log.info('   2. Add wallet addresses to track');
        log.info('   3. The bot will automatically monitor active wallets\n');
      } else {
        log.info(`\n📋 Tracked Wallets: ${trackedWallets.length} total, ${activeWallets.length} active`);
        log.info(`${'─'.repeat(60)}`);
        for (const wallet of trackedWallets) {
          const status = wallet.active ? '✅ ACTIVE' : '⏸️  INACTIVE';
          log.info(`   • ${wallet.address.substring(0, 10)}...${wallet.address.substring(wallet.address.length - 8)} - ${status}`);
        }
        log.info(`${'='.repeat(60)}\n`);
      }

      log.info('🤖 Starting copy trading bot...');
      await startMonitoringServices(copyTrader, null);

      const status = copyTrader.getStatus();

      log.info(`\n${'='.repeat(60)}`);
      log.info(`✅ BOT STARTED SUCCESSFULLY`);
      log.info(`${'='.repeat(60)}`);
      log.info(`   Server: http://localhost:${config.port}`);
      log.info(`   Polling: ${status.running ? '✅ ACTIVE' : '⏸️  INACTIVE'}`);
      log.info(`\n💡 Trading auto-starts on boot; Discovery remains a separate worker process.`);
      log.info(`${'='.repeat(60)}\n`);
      log.info('[Discovery] Discovery now runs as a separate worker process.');
      log.info('[Discovery] Start it in another terminal with: npm run discovery:dev');
    } catch (error: any) {
      log.error({ detail: error.message }, '⚠️  Failed to initialize or start bot')
      log.error('⚠️  Bot will not run, but web server is accessible.');
      log.error('⚠️  Check your configuration and logs.');
      // Don't exit - let the server keep running
    }

    registerAppShutdown(copyTrader, server);
  } catch (error: any) {
    log.error({ detail: error.message }, '❌ Fatal error')
    log.error(error);
    process.exit(1);
  }
}

async function startDiscoveryWorkerRuntime() {
  try {
    await Storage.ensureDataDir();
    await initDatabase();

    const discoveryManager = new DiscoveryManager('worker');
    registerDiscoveryShutdown(discoveryManager);

    const discoveryConfig = discoveryManager.getConfig();
    if (!discoveryConfig.enabled) {
      clearDiscoveryRuntimeHeartbeat();
      console.log('[DiscoveryWorker] Discovery is disabled in config. Enable it from the dashboard before starting the worker.');
      return;
    }

    console.log('🔎 Starting discovery worker...');
    await discoveryManager.start();

    const status = discoveryManager.getStatus();
    console.log(`   Chain listener: ${status.chainListener.connected ? 'connected' : 'disconnected'}`);
    console.log(`   API poller: ${status.apiPoller.running ? 'running' : 'stopped'}`);
    console.log(`   Markets monitored: ${status.apiPoller.marketsMonitored}`);
  } catch (error: any) {
    console.error('❌ Discovery worker failed to start:', error.message);
    console.error(error);
    process.exit(1);
  }
}

/**
 * Main entry point for the Polymarket Copytrade Bot
 */
async function main() {
  const runtimeMode = resolveRuntimeMode(process.env.APP_RUNTIME, process.argv.slice(2));
  const runtimeServices = getRuntimeServicesForMode(runtimeMode);

  if (runtimeServices.discoveryWorker) {
    await startDiscoveryWorkerRuntime();
    return;
  }

  await startAppRuntime();
}

// Run the bot
main().catch((err) => log.error({ err }, 'Unhandled error in main'));
