import { config } from './config.js';
import { CopyTrader } from './copyTrader.js';
import { createServer, startServer } from './server.js';
import { Storage } from './storage.js';
import { initWalletManager } from './walletManager.js';
import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get project root - works whether running from src/ or dist/
const PROJECT_ROOT = process.cwd();

/**
 * Interactive setup - asks for configuration one step at a time
 */
async function runInteractiveSetup(): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false  // Disable special character handling for better paste support
  });

  const question = (prompt: string): Promise<string> => {
    return new Promise((resolve) => {
      process.stdout.write(prompt);
      rl.once('line', (answer) => {
        resolve(answer);
      });
    });
  };

  console.log('\n');
  console.log('═'.repeat(60));
  console.log('   🚀 POLYMARKET COPYTRADE BOT - FIRST TIME SETUP');
  console.log('═'.repeat(60));
  console.log('\nLet\'s get your bot configured! I\'ll ask for each value one at a time.\n');

  try {
    // Step 1: Private Key
    console.log('─'.repeat(60));
    console.log('STEP 1 of 4: Your Wallet Private Key');
    console.log('─'.repeat(60));
    console.log('\nThis is the private key from your crypto wallet.');
    console.log('It should start with "0x" and be 66 characters long.');
    console.log('\n⚠️  IMPORTANT: Never share this with anyone!\n');
    
    const privateKey = await question('Enter your private key: ');
    
    if (!privateKey || !privateKey.trim()) {
      console.log('\n❌ Private key is required. Setup cancelled.\n');
      rl.close();
      return false;
    }

    const trimmedKey = privateKey.trim();
    
    // Basic validation
    if (!trimmedKey.startsWith('0x')) {
      console.log('\n⚠️  Warning: Private key usually starts with "0x"');
    }
    if (trimmedKey.length !== 66) {
      console.log(`⚠️  Warning: Private key length is ${trimmedKey.length}, expected 66`);
    }

    // Step 2: Builder API Key
    console.log('\n');
    console.log('─'.repeat(60));
    console.log('STEP 2 of 4: Polymarket Builder API Key');
    console.log('─'.repeat(60));
    console.log('\nGo to: https://polymarket.com/settings?tab=builder');
    console.log('Click "Create API Key" and copy the API Key here.\n');
    console.log('(This is REQUIRED for trading to work)\n');
    
    const builderApiKey = await question('Enter your Builder API Key: ');
    
    if (!builderApiKey || !builderApiKey.trim()) {
      console.log('\n⚠️  Warning: Without Builder API credentials, trading will fail!');
    }

    // Step 3: Builder Secret
    console.log('\n');
    console.log('─'.repeat(60));
    console.log('STEP 3 of 4: Polymarket Builder API Secret');
    console.log('─'.repeat(60));
    console.log('\nThis is shown once when you create the API key.');
    console.log('If you didn\'t save it, you may need to create a new key.\n');
    
    const builderSecret = await question('Enter your Builder API Secret: ');

    // Step 4: Builder Passphrase
    console.log('\n');
    console.log('─'.repeat(60));
    console.log('STEP 4 of 4: Polymarket Builder API Passphrase');
    console.log('─'.repeat(60));
    console.log('\nThis is the passphrase you created with your API key.\n');
    
    const builderPassphrase = await question('Enter your Builder API Passphrase: ');

    rl.close();

    // Create the .env file
    const envContent = `# Polymarket Copytrade Bot Configuration
# Generated by setup wizard

# Your wallet private key (NEVER commit this to git!)
PRIVATE_KEY=${trimmedKey}

# Polymarket Builder API credentials (REQUIRED for trading!)
# Get these from: https://polymarket.com/settings?tab=builder
POLYMARKET_BUILDER_API_KEY=${builderApiKey?.trim() || ''}
POLYMARKET_BUILDER_SECRET=${builderSecret?.trim() || ''}
POLYMARKET_BUILDER_PASSPHRASE=${builderPassphrase?.trim() || ''}

# Polymarket API endpoints (use defaults)
POLYMARKET_CLOB_API_URL=https://clob.polymarket.com
POLYMARKET_DATA_API_URL=https://data-api.polymarket.com
POLYMARKET_GAMMA_API_URL=https://gamma-api.polymarket.com

# Polygon RPC endpoint
POLYGON_RPC_URL=https://polygon-rpc.com

# Signature type (0 = EOA wallet, 1 = Proxy wallet, 2 = Gnosis Safe)
# If you connected MetaMask directly, use 0
# If you signed up via email, use 1
POLYMARKET_SIGNATURE_TYPE=0

# Server configuration
PORT=3001

# Monitoring interval (5 seconds for fast copy trading)
MONITORING_INTERVAL_MS=5000

# Data directory
DATA_DIR=./data
`;

    // Write to .env file in project root
    const envPath = join(PROJECT_ROOT, '.env');
    
    console.log(`\n[DEBUG] Writing .env to: ${envPath}`);
    
    writeFileSync(envPath, envContent, 'utf-8');
    
    console.log('\n');
    console.log('═'.repeat(60));
    console.log('   ✅ SETUP COMPLETE!');
    console.log('═'.repeat(60));
    console.log(`\nYour configuration has been saved to: ${envPath}`);
    console.log('\nRestarting bot with your new configuration...\n');
    
    return true;

  } catch (error: any) {
    console.error('\n❌ Setup failed:', error.message);
    rl.close();
    return false;
  }
}

/**
 * Check if configuration exists and is valid
 */
function isConfigured(): boolean {
  const envPath = join(PROJECT_ROOT, '.env');
  
  console.log(`[DEBUG] Checking for .env at: ${envPath}`);
  
  // Check if .env file exists
  if (!existsSync(envPath)) {
    console.log(`[DEBUG] .env file does not exist`);
    return false;
  }
  
  // Check if PRIVATE_KEY is set (not just placeholder)
  try {
    const envContent = readFileSync(envPath, 'utf-8');
    // Just check that PRIVATE_KEY has some value (not empty or placeholder)
    const hasPrivateKey = envContent.includes('PRIVATE_KEY=') && 
                          !envContent.includes('PRIVATE_KEY=your_private_key_here') &&
                          !envContent.includes('PRIVATE_KEY=\n') &&
                          !envContent.includes('PRIVATE_KEY=$');
    console.log(`[DEBUG] .env exists, hasPrivateKey: ${hasPrivateKey}`);
    return hasPrivateKey;
  } catch (err) {
    console.log(`[DEBUG] Error reading .env: ${err}`);
    return false;
  }
}

/**
 * Reload config after setup
 */
function reloadConfig(): void {
  // Re-read .env file
  const envPath = join(PROJECT_ROOT, '.env');
  
  if (existsSync(envPath)) {
    const envContent = readFileSync(envPath, 'utf-8');
    const lines = envContent.split('\n');
    
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...valueParts] = trimmed.split('=');
        const value = valueParts.join('='); // Handle values with = in them
        if (key && value !== undefined) {
          process.env[key] = value;
        }
      }
    }
  }
  
  // Update config object
  config.privateKey = process.env.PRIVATE_KEY || '';
  config.polymarketBuilderApiKey = process.env.POLYMARKET_BUILDER_API_KEY || '';
  config.polymarketBuilderSecret = process.env.POLYMARKET_BUILDER_SECRET || '';
  config.polymarketBuilderPassphrase = process.env.POLYMARKET_BUILDER_PASSPHRASE || '';
}

/**
 * Main entry point for the Polymarket Copytrade Bot
 */
async function main() {
  let copyTrader: CopyTrader | null = null;
  
  try {
    // Ensure data directory exists (always do this, even if config fails)
    await Storage.ensureDataDir();

    // Check if configuration exists
    if (!isConfigured()) {
      console.log('\n🔧 No configuration found. Starting setup wizard...');
      
      const setupSuccess = await runInteractiveSetup();
      
      if (!setupSuccess) {
        console.log('\n❌ Setup was not completed. Please run "npm run dev" again to try setup.\n');
        process.exit(1);
      }
      
      // Reload configuration after setup
      reloadConfig();
    }

    // Initialize wallet manager early (so trading wallets are available to API routes)
    console.log('🔑 Loading trading wallets...');
    await initWalletManager();

    // Create and start web server first (so it's accessible even if bot init fails)
    console.log('🌐 Starting web server...');
    copyTrader = new CopyTrader();
    const app = await createServer(copyTrader);
    await startServer(app);

    // Validate configuration
    console.log('🔧 Validating configuration...');
    try {
      config.validate();
    } catch (error: any) {
      console.error('⚠️  Configuration validation failed:', error.message);
      console.error('⚠️  Bot will not start, but web server is running.');
      console.error('⚠️  Please fix your configuration and restart.');
      // Don't exit - let the server keep running so user can see the error
      return;
    }

    // Initialize copy trader
    console.log('🚀 Initializing copy trader...');
    try {
      await copyTrader.initialize();

      // Check if there are any tracked wallets
      const trackedWallets = await Storage.getActiveWallets();
      const activeWallets = trackedWallets.filter(w => w.active);
      
      console.log(`\n${'='.repeat(60)}`);
      console.log(`📊 BOT STATUS`);
      console.log(`${'='.repeat(60)}`);
      
      if (trackedWallets.length === 0) {
        console.log('\n⚠️  WARNING: No wallets are being tracked!');
        console.log('   To start copy trading:');
        console.log('   1. Open the web dashboard at http://localhost:' + config.port);
        console.log('   2. Add wallet addresses to track');
        console.log('   3. The bot will automatically start monitoring them\n');
      } else {
        console.log(`\n📋 Tracked Wallets: ${trackedWallets.length} total, ${activeWallets.length} active`);
        console.log(`${'─'.repeat(60)}`);
        for (const wallet of trackedWallets) {
          const status = wallet.active ? '✅ ACTIVE' : '⏸️  INACTIVE';
          console.log(`   • ${wallet.address.substring(0, 10)}...${wallet.address.substring(wallet.address.length - 8)} - ${status}`);
        }
        console.log(`${'='.repeat(60)}\n`);
      }

      // Start the copy trading bot
      console.log('🤖 Starting copy trading bot...');
      await copyTrader.start();
      
      // Get status after starting
      const status = copyTrader.getStatus();
      const domeWs = status.domeWs;

      console.log(`\n${'='.repeat(60)}`);
      console.log(`✅ BOT STARTED SUCCESSFULLY`);
      console.log(`${'='.repeat(60)}`);
      console.log(`Monitoring Methods:`);
      console.log(`   🌐 Dome WebSocket: ${domeWs?.connected ? '✅ CONNECTED' : '⏳ Not connected'} — ${domeWs?.trackedWallets ?? 0} wallets`);
      console.log(`   🔄 Polling: ${status.running ? '✅ ACTIVE' : '⏸️  INACTIVE'}`);
      console.log(`\n💡 Status: ${domeWs?.connected ? 'Real-time (Dome) + polling' : 'Polling mode'}`);
      console.log(`${'='.repeat(60)}\n`);
    } catch (error: any) {
      console.error('⚠️  Failed to initialize or start bot:', error.message);
      console.error('⚠️  Bot will not run, but web server is accessible.');
      console.error('⚠️  Check your configuration and logs.');
      // Don't exit - let the server keep running
    }

    // Handle graceful shutdown
    process.on('SIGINT', () => {
      console.log('\n🛑 Shutting down...');
      if (copyTrader) {
        copyTrader.stop();
      }
      process.exit(0);
    });

    process.on('SIGTERM', () => {
      console.log('\n🛑 Shutting down...');
      if (copyTrader) {
        copyTrader.stop();
      }
      process.exit(0);
    });

  } catch (error: any) {
    console.error('❌ Fatal error:', error.message);
    console.error(error);
    process.exit(1);
  }
}

// Run the bot
main().catch(console.error);
